lang: ko                    # 한국어로 변경
timezone: Asia/Seoul        # 한국 시간대로 변경

title: Your Blog Title      # 실제 블로그 제목으로 변경
tagline: Your Blog Tagline  # 적절한 부제목으로 변경
description: >-             # SEO를 위한 설명 추가
  여기에 블로그에 대한 설명을 작성하세요.

# GitHub 정보 업데이트
github:
  username: Ji-Ha

# 개인 정보 업데이트
social:
  name: 노지환
  email: xodhkd36@gmail.com
  links:
    - https://github.com/Ji-Ha  # GitHub 링크 업데이트

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-include-cache